site_name: Minium Core
pages:
  - ['third-parties.md']
  - ['changelog.md']
  - ['core/concepts.md', 'Introduction']
  - ['core/best-practices.md', 'Introduction']
  - ['api/web-elements.md', 'API']
  - ['api/interactable.md', 'API']
  - ['api/browser.md', 'API']
  - ['api/configuration.md', 'API']
  - ['api/assertions.md', 'API']
site_dir: '${static.docs.dir}'
theme: ''
theme_dir: 'readthedocs-minium'
