site_name: Minium Core
pages:
  - ['index.md', 'Introduction']
  - ['third-parties.md']
  - ['changelog.md']
  - ['introduction/getting-started.md', 'Introduction']
  - ['introduction/concepts.md', 'Introduction']
  - ['introduction/best-practices.md', 'Introduction']
  - ['api/web-elements.md', 'API']
  - ['api/interactable.md', 'API']
  - ['api/browser.md', 'API']
  - ['api/configuration.md', 'API']
site_dir: '${static.docs.dir}'
theme: readthedocs
